### ISSUE TITLE
Eval example?

### ISSUE THREAD

**Issue by alteraa** [Leadmatic/tinyChat#1]
Any chance to add evaluation example or full code? That would be very insightful to newbies like me :)

Thanks for this cool repo.

**Comment by kishb87** [comment]
Yes, I will get that up by tomorrow evening!

**Comment by kishb87** [comment]
I included some out examples and how to run inference. Let me know if that's helpful. Will close the issue for now. Thanks!

**Comment by alteraa** [comment]
Thank you!

But, I was actually referencing these [scores](https://huggingface.co/Leadmatic/tinyChat#benchmark) to check my custom model's performance.

**Comment by kishb87** [comment]
Ah, you'll want to use the[ lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness) for that. If you look at their readme, there's a section on evaluation for peft models.
